[package]
name = "dmenu"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
freedesktop_entry_parser = "1.3.0"
fuzzy-matcher = "0.3.7"
nix = { version = "0.28.0", features = ["process"] }
ratatui = "0.26.2"
